### ISSUE TITLE
unable to draw tree

### ISSUE THREAD

**Issue by amit4mchiba** [hahnlab/CAFE#60]
Hi,

I am new to CAFE, and was first trying the tutorial to get to the final results. 

Thanks for such a nice description, I was able to get all results but now I am stuck at drawing the tree. I tried this command as mentioned in the tutorial-
python ../python_scripts/cafetutorial_draw_tree.py -i summary_run1_node.txt -t '((((cat:68.7105,horse:68.7105):4.56678,cow:73.2773):20.7227,(((((chimp:4.44417,human:4.44417):6.68268,orang:11.1268):2.28586,gibbon:13.4127):7.21153,(macaque:4.56724,baboon:4.56724):16.057):16.0607,marmoset:36.6849):57.3151):38.738,(rat:36.3024,mouse:36.3024):96.4356)' -d '((((cat<0>,horse<2>)<1>,cow<4>)<3>,(((((chimp<6>,human<8>)<7>,orang<10>)<9>,gibbon<12>)<11>,(macaque<14>,baboon<16>)<15>)<13>,marmoset<18>)<17>)<5>,(rat<20>,mouse<22>)<21>)<19>' -o summary_run1_tree_rapid1.png -y Rapid                             

And got this error-
Traceback (most recent call last):
  File "../python_scripts/cafetutorial_draw_tree.py", line 83, in <module>
    draw_tree(args.input_file, args.tree_type, args.tree, args.id_tree, args.output_file)
  File "../python_scripts/cafetutorial_draw_tree.py", line 57, in draw_tree
    fig = plt.figure(frameon=False)
  File "/home/amit8chiba/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/home/amit8chiba/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/amit8chiba/.local/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/amit8chiba/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Please advice me on how shall I proceed.

thank you so much in advance,

with best regards
Amit

**Comment by benfulton** [comment]
It sounds like you're trying to draw a figure on a system that doesn't have any graphics support. Please take a look at the answers here:

https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

and see if one of them is applicable to your situation.
