### ISSUE TITLE
CAFE Report File Analysis error

### ISSUE THREAD

**Issue by CLAIRE-cuhk** [hahnlab/CAFE#85]
Hello,

I encountered an error when I try to parse the cafe report. I found a similar issue posted before and saying this error below is caused by the additional internal node label. I tried to delete the internal node labels in the input tree to fix the problem but didn't work.  Can anyone tell me which exact part should I delete? 

Here is my original tree:
(Drosophilamelanogaster:155.769,(Muscadomestica:140.192,(((Aedesaegypti:41.5384,Culexquinquefasciatus:41.5384)1:41.5384,(Anophelesgambiae:41.5384,Anophelesstephensi:41.5384)1:41.5384)1:41.5384,(Triboliumcastaneum:109.038,((((Pediculushumanuscorporis:31.1538,Frankliniellaoccidentalis:31.1538)1:31.1538,(Blattellagermanica:46.7307,((Zootermopsisnevadensis:15.5769,Cryptotermessecundus:15.5769)1:15.5769,Periplanetaamericana:31.1538)1:15.5769)1:15.5769)1:15.5769,((Cimexlectularius:25.9615,Cinaracedri:25.9615)83.6:25.9615,Laodelphaxstriatellus:51.923)1:25.9615)1:15.5769,(Apismellifera:74.7691,(Linepithemahumil:56.0768,((Nylanderiafulva:18.6923,Camponotusfloridanus:18.6923)1:18.6923,(Monomoriumpharaonis:18.6923,Cyphomyrmexcostatus:18.6923)1:18.6923)1:18.6923)1:18.6923)1:18.6923)1:15.5769)1:15.5769)1:15.5769)1:15.5769)
=======================================================================
		CAFE Report File Analysis
		09.21.2020 | 10:24:20
---------
Parsing format information...

---------
Initializing output structures...

---------
Counting changes per branch...
                                                                                                                        [*-------------------------------------------------] 0.061% complete.Traceback (most recent call last):
  File "./cafetutorial_report_analysis.py", line 371, in <module>
    results_main, node_fams_main = cra(inlines_main, results_main, node_fams_main, linestart_main, ancfilename, sorted_nodes, 1);
  File "./cafetutorial_report_analysis.py", line 193, in cra
    anccount = int(tlinfo[curanc][4]);
ValueError: invalid literal for int() with base 10: '4_11'

**Comment by gwct** [comment]
Hi,
I think this is happening because the report_analysis script unfortunately
can't handle node labels on the tree. All of your internal nodes seem to
have the label '1' (except for one that is '83.6'). These labels get
carried over to each gene family tree in the CAFE output.
To fix, you can either re-run CAFE without the internal labels on the
original tree, or remove the labels from all trees in the CAFE report file
with some regex.
Let us know if you need any more help!
-Gregg Thomas

**Comment by CLAIRE-cuhk** [comment]
> Hi, I think this is happening because the report_analysis script unfortunately can't handle node labels on the tree. All of your internal nodes seem to have the label '1' (except for one that is '83.6'). These labels get carried over to each gene family tree in the CAFE output. To fix, you can either re-run CAFE without the internal labels on the original tree, or remove the labels from all trees in the CAFE report file with some regex. Let us know if you need any more help! -Gregg Thomas

Many thanks for your help!
I was able to finish the run after removing all internal node labels.
