### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mictadlo** [hahnlab/CAFE#92]
Hi, 
I tried all different RaXML outputs with `cafetutorial_prep_r8s.py` but it always returns `IndexError: tuple index out of range`

```
$ python ~/projects/cafe/cafetutorial_prep_r8s.py -i RAxML_bestTree.outRaxml -o r8s_ctl_file.txt -s 97377 -p "AT SMEL transcript:OI Nitab4.5 Solyc1 Sotub nlab nqld" -c ’29.8’

Running cafetutorial_clade_and_size_filter.py as a standalone...

Traceback (most recent call last):
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 61, in <module>
    r8s_prep(args.input_file, args.sites_n, list_of_spp_tuples, list_of_cal_points, args.output_file)
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 31, in r8s_prep
    node_name = pair[0][-3:] + pair[1][-3:]
IndexError: tuple index out of range

$ python ~/projects/cafe/cafetutorial_prep_r8s.py -i RAxML_bipartitions.outRaxml -o r8s_ctl_file.txt -s 97377 -p "AT SMEL transcript:OI Nitab4.5 Solyc1 Sotub nlab nqld" -c ’29.8’

Running cafetutorial_clade_and_size_filter.py as a standalone...

Traceback (most recent call last):
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 61, in <module>
    r8s_prep(args.input_file, args.sites_n, list_of_spp_tuples, list_of_cal_points, args.output_file)
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 31, in r8s_prep
    node_name = pair[0][-3:] + pair[1][-3:]
IndexError: tuple index out of range
(cafe) ubuntu@ip-10-0-1-246:/mnt/volume1/orthoset2/phylopipe/src$ python ~/projects/cafe/cafetutorial_prep_r8s.py -i RAxML_bipartitionsBranchLabels.outRaxml -o r8s_ctl_file.txt -s 97377 -p "AT SMEL transcript:OI Nitab4.5 Solyc1 Sotub nlab nqld" -c ’29.8’

Running cafetutorial_clade_and_size_filter.py as a standalone...

Traceback (most recent call last):
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 61, in <module>
    r8s_prep(args.input_file, args.sites_n, list_of_spp_tuples, list_of_cal_points, args.output_file)
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 31, in r8s_prep
    node_name = pair[0][-3:] + pair[1][-3:]
IndexError: tuple index out of range

$ python ~/projects/cafe/cafetutorial_prep_r8s.py -i RAxML_info.outRaxml -o r8s_ctl_file.txt -s 97377 -p "AT SMEL transcript:OI Nitab4.5 Solyc1 Sotub nlab nqld" -c ’29.8’

Running cafetutorial_clade_and_size_filter.py as a standalone...

Traceback (most recent call last):
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 61, in <module>
    r8s_prep(args.input_file, args.sites_n, list_of_spp_tuples, list_of_cal_points, args.output_file)
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 31, in r8s_prep
    node_name = pair[0][-3:] + pair[1][-3:]
IndexError: tuple index out of range
(cafe) ubuntu@ip-10-0-1-246:/mnt/volume1/orthoset2/phylopipe/src$ python ~/projects/cafe/cafetutorial_prep_r8s.py -i RAxML_bootstrap.outRaxml -o r8s_ctl_file.txt -s 97377 -p "AT SMEL transcript:OI Nitab4.5 Solyc1 Sotub nlab nqld" -c ’29.8’

Running cafetutorial_clade_and_size_filter.py as a standalone...

Traceback (most recent call last):
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 61, in <module>
    r8s_prep(args.input_file, args.sites_n, list_of_spp_tuples, list_of_cal_points, args.output_file)
  File "/home/ubuntu/projects/cafe/cafetutorial_prep_r8s.py", line 31, in r8s_prep
    node_name = pair[0][-3:] + pair[1][-3:]
IndexError: tuple index out of range
```
What did I miss?

Thank you in advance,

Michal

**Comment by benfulton** [comment]
Hi,

Please submit usage questions to the mailing list here: https://groups.google.com/forum/#!forum/hahnlabcafe

Thanks.

**Comment by mictadlo** [comment]
Hi, I've just posted it.
